import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import type { CartItem } from "../types";

type CartState = {
    cart: CartItem[];                           //This defines the shape of the cart state, which is an array of CartItem objects. Each CartItem represents an item in the shopping cart, including its id, name, price, and quantity.
};

const initialState: CartState = {
  cart: [],                                             // initially Cart when start should always be empty so: cart[]
};

//Creating a “feature module” that contains:
const cartSlice = createSlice({                  
    name: "cart",                                   
    initialState,                                        //state (initialState) what was 1st in cart base-state.
    reducers:{                                          //logic (reducers) and actions (auto-generated). change comes from dispatching actions that trigger the reducers to update the state.

    // ---------------- ADD ITEM ----------------
    addItem(state, action: PayloadAction<CartItem>) {                  // item you want to add in cart is in action.payload.
      const existing = state.cart.find(                                //checking if the item you’re trying to add already exists in the cart by looping through the cart and tries to find a matching item
        (item) => item.id === action.payload.id
      );

      if (existing) {
        existing.quantity += action.payload.quantity;
      } else {
        state.cart.push(action.payload);                                         // add new item to cart if it doesn't exit.
      }
    },

    // ---------------- INCREASE ----------------
    increaseQty(state, action: PayloadAction<number>) {                                //a number (ID of the item) is in action.payload. 
      const item = state.cart.find((i) => i.id === action.payload);                                   // loops through the cart to find the item with the matching ID.
      if (item) item.quantity += 1;                                                       
    },

    // ---------------- DECREASE ----------------
    decreaseQty(state, action: PayloadAction<number>) {
      const item = state.cart.find((i) => i.id === action.payload);

      if (item) {
        item.quantity -= 1;
      }

      // remove items with 0 qty (same as your filter logic)
      state.cart = state.cart.filter((item) => item.quantity > 0);
    },

    // ---------------- DELETE ITEM ----------------
    deleteItem(state, action: PayloadAction<number>) {
      state.cart = state.cart.filter(
        (item) => item.id !== action.payload
      );
    },

    // ---------------- CLEAR CART ----------------
    clearCart(state) {
      state.cart = [];
    },
  },
});

export const {                         //cartSlice.actions and cartSlice.reducer are auto-generated by createSlice based on the reducers you defined.
  addItem,
  increaseQty,
  decreaseQty,
  deleteItem,
  clearCart,
} = cartSlice.actions;

export default cartSlice.reducer;
